version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_collection
      MYSQL_USER: nathan
      MYSQL_PASSWORD: 444719
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
