version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_collection
      MYSQL_USER: nathan
      MYSQL_PASSWORD: 444719
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql  # Ajout du volume pour la persistance des données
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:  # Définition du volume pour la persistance des données
